<? php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">';
echo '<title>Navy IFN Login</title>';
echo '<link rel="stylesheet" type="text/css" href="css/bootstrap.css">';
echo '<link rel="stylesheet" type="text/css" href="css/main.css">';
echo '<link rel="stylesheet" type="text/css" href="css/mediaquery.css">';
echo '<link rel="stylesheet" type="text/css" href="css/login.css">';
echo '<link rel="stylesheet" type="text/css" href="css/waves.css">';
echo '<link href="https://fonts.googleapis.com/css?family=Titillium+Web:200,400" rel="stylesheet">';
echo '</head>';
echo '<body>';
echo '';
echo '<nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">';
echo '<a class="navbar-brand" href="index.html"><img src="images/navylogo.png" width="60" height="60" ></a>';
echo '<div class="collapse navbar-collapse" id="navbarNavAltMarkup">';
echo '<div class="navbar-nav ml-auto">';
echo '<a class="nav-item nav-link buttonStyle" href="index.html">Home</a>';
echo '<a class="nav-item nav-link buttonStyle" href="roster.html">Roster</a>';
echo '<a class="nav-item nav-link buttonStyle" href="documents.html">Documents</a>';
echo '<a class="nav-item nav-link buttonStyle" href="login.html">Login</a>';
echo '<div id="loggedin" style="display:none">Logged in!</div>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '';
echo '<div class="waves">';
echo '<div class="wave wave_1"></div>';
echo '<div class="wave wave_2"></div>';
echo '<div class="wave wave_3"></div>';
echo '<div class="wave wave_4"></div>';
echo '<div class="wave wave_5"></div>';
echo '</div>';
echo '';
echo '<div class="loginform">';
echo '<div class="login-page">';
echo '<div class="form">';
echo '<form class="login-form" method="post" action="authen_login.php">';
echo '<input type="text" placeholder="Username" name="username"/>';
echo '<input type="password" placeholder="Password" name="userpass"/>';
echo '<button type="submit" onclick="login(form)" class="buttonStyle">login</button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Bootstrap javascript - DON'T DELETE -->';
echo '<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>';
echo '<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>';
echo '<script src="js/login.js"></script>';
echo '</body>';
echo '</html>';
echo '';
?>